// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mail} from '../models';
import {context} from '../models';

export function ConnectGmail():Promise<mail.Account>;

export function DisconnectGmail():Promise<void>;

export function GetAccounts():Promise<Array<mail.Account>>;

export function GetActivity():Promise<Array<mail.Activity>>;

export function GetCategories():Promise<Array<mail.Category>>;

export function GetMails():Promise<Array<mail.Mail>>;

export function GetRules():Promise<Array<mail.Rule>>;

export function GmailConfigured():Promise<boolean>;

export function GmailConnected():Promise<boolean>;

export function RefreshMails():Promise<void>;

export function SendReply(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;
