// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectGmail() {
  return window['go']['main']['MailService']['ConnectGmail']();
}

export function DisconnectGmail() {
  return window['go']['main']['MailService']['DisconnectGmail']();
}

export function GetAccounts() {
  return window['go']['main']['MailService']['GetAccounts']();
}

export function GetActivity() {
  return window['go']['main']['MailService']['GetActivity']();
}

export function GetCategories() {
  return window['go']['main']['MailService']['GetCategories']();
}

export function GetMails() {
  return window['go']['main']['MailService']['GetMails']();
}

export function GetRules() {
  return window['go']['main']['MailService']['GetRules']();
}

export function GmailConfigured() {
  return window['go']['main']['MailService']['GmailConfigured']();
}

export function GmailConnected() {
  return window['go']['main']['MailService']['GmailConnected']();
}

export function RefreshMails() {
  return window['go']['main']['MailService']['RefreshMails']();
}

export function SendReply(arg1, arg2, arg3) {
  return window['go']['main']['MailService']['SendReply'](arg1, arg2, arg3);
}

export function Start(arg1) {
  return window['go']['main']['MailService']['Start'](arg1);
}
