// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['main']['MailService']['GetAccounts']();
}

export function GetActivity() {
  return window['go']['main']['MailService']['GetActivity']();
}

export function GetCategories() {
  return window['go']['main']['MailService']['GetCategories']();
}

export function GetMails() {
  return window['go']['main']['MailService']['GetMails']();
}

export function GetRules() {
  return window['go']['main']['MailService']['GetRules']();
}
