// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mail} from '../models';

export function GetAccounts():Promise<Array<mail.Account>>;

export function GetActivity():Promise<Array<mail.Activity>>;

export function GetCategories():Promise<Array<mail.Category>>;

export function GetMails():Promise<Array<mail.Mail>>;

export function GetRules():Promise<Array<mail.Rule>>;
